try {
  console.log(a);
  let a = 3;
} catch (error) {
  console.log("let перед использованием нужно объявить");
}
